services:
  web:
    image: hak2881/senior:latest
    container_name: fast-app-dev
    working_dir: /app
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env/.dev.env
    environment:
      - ENV=dev
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: postgres-db-dev
    restart: always
    environment:
      POSTGRES_DB: 'senior'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1q2w3e4r'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    container_name: redis-dev
    restart: always
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    container_name: nginx-dev
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
